INFO 2024-11-20 19:45:43,763 autoreload Watching for file changes with StatReloader
DEBUG 2024-11-20 19:45:46,497 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 19:45:46,564 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 19:48:15,601 autoreload Watching for file changes with StatReloader
WARNING 2024-11-20 19:48:20,241 log Not Found: /favicon.ico
DEBUG 2024-11-20 19:48:28,297 views Selected items on GET: []
DEBUG 2024-11-20 19:48:31,460 views Selected items on GET: []
INFO 2024-11-20 19:56:18,157 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\models.py changed, reloading.
DEBUG 2024-11-20 19:56:18,157 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 19:56:18,745 autoreload Watching for file changes with StatReloader
DEBUG 2024-11-20 19:56:55,536 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 19:56:55,581 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 19:57:01,896 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 19:58:02,113 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:00:18,701 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:01:01,059 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:03:51,330 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:08:05,109 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:14:24,264 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:15:40,850 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:16:55,310 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:21:25,096 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:21:30,396 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:21:58,411 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:22:19,553 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:22:29,347 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:22:52,207 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:22:52,815 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:23:04,944 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:23:05,600 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:23:06,383 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:23:06,964 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:23:59,049 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:23:59,841 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:24:00,727 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:24:01,409 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:25:00,713 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:25:01,450 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:25:12,032 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:25:18,515 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:25:58,765 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:25:59,384 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:27:20,398 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:29:55,450 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:30:38,334 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:30:38,836 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:31:06,898 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:31:07,482 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:32:52,797 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:32:53,389 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 20:33:14,558 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:33:50,898 autoreload Watching for file changes with StatReloader
DEBUG 2024-11-20 20:34:04,600 proactor_events Using proactor: IocpProactor
ERROR 2024-11-20 20:34:22,647 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\homepage\views.py", line 51, in home_view
    medicine_shortage = Stock.objects.filter(quantity__lt=F('threshold'), is_deleted=False).count()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1260, in build_filter
    value = self.resolve_lookup_value(value, can_reuse, allow_joins, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1069, in resolve_lookup_value
    value = value.resolve_expression(self, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\expressions.py", line 532, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1685, in resolve_ref
    join_info = self.setup_joins(field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1567, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1483, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'threshold' into field. Choices are: brand_name, cartitem, dosage_strength, expiry_date, form, generic_name, history, is_deleted, item_no, last_updated, purchaseitems, quantity, saleitem
ERROR 2024-11-20 20:37:41,468 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\homepage\views.py", line 51, in home_view
    medicine_shortage = Stock.objects.filter(quantity__lt=F('threshold'), is_deleted=False).count()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1260, in build_filter
    value = self.resolve_lookup_value(value, can_reuse, allow_joins, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1069, in resolve_lookup_value
    value = value.resolve_expression(self, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\expressions.py", line 532, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1685, in resolve_ref
    join_info = self.setup_joins(field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1567, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1483, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'threshold' into field. Choices are: brand_name, cartitem, dosage_strength, expiry_date, form, generic_name, history, is_deleted, item_no, last_updated, purchaseitems, quantity, saleitem
ERROR 2024-11-20 20:37:42,241 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\homepage\views.py", line 51, in home_view
    medicine_shortage = Stock.objects.filter(quantity__lt=F('threshold'), is_deleted=False).count()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1260, in build_filter
    value = self.resolve_lookup_value(value, can_reuse, allow_joins, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1069, in resolve_lookup_value
    value = value.resolve_expression(self, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\expressions.py", line 532, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1685, in resolve_ref
    join_info = self.setup_joins(field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1567, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1483, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'threshold' into field. Choices are: brand_name, cartitem, dosage_strength, expiry_date, form, generic_name, history, is_deleted, item_no, last_updated, purchaseitems, quantity, saleitem
ERROR 2024-11-20 20:37:42,451 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\homepage\views.py", line 51, in home_view
    medicine_shortage = Stock.objects.filter(quantity__lt=F('threshold'), is_deleted=False).count()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1260, in build_filter
    value = self.resolve_lookup_value(value, can_reuse, allow_joins, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1069, in resolve_lookup_value
    value = value.resolve_expression(self, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\expressions.py", line 532, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1685, in resolve_ref
    join_info = self.setup_joins(field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1567, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1483, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'threshold' into field. Choices are: brand_name, cartitem, dosage_strength, expiry_date, form, generic_name, history, is_deleted, item_no, last_updated, purchaseitems, quantity, saleitem
ERROR 2024-11-20 20:37:42,660 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\homepage\views.py", line 51, in home_view
    medicine_shortage = Stock.objects.filter(quantity__lt=F('threshold'), is_deleted=False).count()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1260, in build_filter
    value = self.resolve_lookup_value(value, can_reuse, allow_joins, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1069, in resolve_lookup_value
    value = value.resolve_expression(self, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\expressions.py", line 532, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1685, in resolve_ref
    join_info = self.setup_joins(field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1567, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1483, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'threshold' into field. Choices are: brand_name, cartitem, dosage_strength, expiry_date, form, generic_name, history, is_deleted, item_no, last_updated, purchaseitems, quantity, saleitem
ERROR 2024-11-20 20:37:42,852 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\homepage\views.py", line 51, in home_view
    medicine_shortage = Stock.objects.filter(quantity__lt=F('threshold'), is_deleted=False).count()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1260, in build_filter
    value = self.resolve_lookup_value(value, can_reuse, allow_joins, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1069, in resolve_lookup_value
    value = value.resolve_expression(self, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\expressions.py", line 532, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1685, in resolve_ref
    join_info = self.setup_joins(field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1567, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1483, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'threshold' into field. Choices are: brand_name, cartitem, dosage_strength, expiry_date, form, generic_name, history, is_deleted, item_no, last_updated, purchaseitems, quantity, saleitem
ERROR 2024-11-20 20:37:43,054 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\homepage\views.py", line 51, in home_view
    medicine_shortage = Stock.objects.filter(quantity__lt=F('threshold'), is_deleted=False).count()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1260, in build_filter
    value = self.resolve_lookup_value(value, can_reuse, allow_joins, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1069, in resolve_lookup_value
    value = value.resolve_expression(self, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\expressions.py", line 532, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1685, in resolve_ref
    join_info = self.setup_joins(field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1567, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1483, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'threshold' into field. Choices are: brand_name, cartitem, dosage_strength, expiry_date, form, generic_name, history, is_deleted, item_no, last_updated, purchaseitems, quantity, saleitem
ERROR 2024-11-20 20:37:43,227 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\homepage\views.py", line 51, in home_view
    medicine_shortage = Stock.objects.filter(quantity__lt=F('threshold'), is_deleted=False).count()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1260, in build_filter
    value = self.resolve_lookup_value(value, can_reuse, allow_joins, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1069, in resolve_lookup_value
    value = value.resolve_expression(self, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\expressions.py", line 532, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1685, in resolve_ref
    join_info = self.setup_joins(field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1567, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1483, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'threshold' into field. Choices are: brand_name, cartitem, dosage_strength, expiry_date, form, generic_name, history, is_deleted, item_no, last_updated, purchaseitems, quantity, saleitem
ERROR 2024-11-20 20:38:14,985 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\homepage\views.py", line 51, in home_view
    medicine_shortage = Stock.objects.filter(quantity__lt=F('threshold'), is_deleted=False).count()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1260, in build_filter
    value = self.resolve_lookup_value(value, can_reuse, allow_joins, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1069, in resolve_lookup_value
    value = value.resolve_expression(self, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\expressions.py", line 532, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1685, in resolve_ref
    join_info = self.setup_joins(field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1567, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1483, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'threshold' into field. Choices are: brand_name, cartitem, dosage_strength, expiry_date, form, generic_name, history, is_deleted, item_no, last_updated, purchaseitems, quantity, saleitem
ERROR 2024-11-20 20:38:15,760 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\homepage\views.py", line 51, in home_view
    medicine_shortage = Stock.objects.filter(quantity__lt=F('threshold'), is_deleted=False).count()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1260, in build_filter
    value = self.resolve_lookup_value(value, can_reuse, allow_joins, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1069, in resolve_lookup_value
    value = value.resolve_expression(self, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\expressions.py", line 532, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1685, in resolve_ref
    join_info = self.setup_joins(field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1567, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1483, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'threshold' into field. Choices are: brand_name, cartitem, dosage_strength, expiry_date, form, generic_name, history, is_deleted, item_no, last_updated, purchaseitems, quantity, saleitem
ERROR 2024-11-20 20:38:20,153 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\homepage\views.py", line 51, in home_view
    medicine_shortage = Stock.objects.filter(quantity__lt=F('threshold'), is_deleted=False).count()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1260, in build_filter
    value = self.resolve_lookup_value(value, can_reuse, allow_joins, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1069, in resolve_lookup_value
    value = value.resolve_expression(self, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\expressions.py", line 532, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1685, in resolve_ref
    join_info = self.setup_joins(field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1567, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1483, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'threshold' into field. Choices are: brand_name, cartitem, dosage_strength, expiry_date, form, generic_name, history, is_deleted, item_no, last_updated, purchaseitems, quantity, saleitem
ERROR 2024-11-20 20:38:23,668 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\homepage\views.py", line 51, in home_view
    medicine_shortage = Stock.objects.filter(quantity__lt=F('threshold'), is_deleted=False).count()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1260, in build_filter
    value = self.resolve_lookup_value(value, can_reuse, allow_joins, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1069, in resolve_lookup_value
    value = value.resolve_expression(self, **kwargs)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\expressions.py", line 532, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize, simple_col)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1685, in resolve_ref
    join_info = self.setup_joins(field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1567, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1483, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'threshold' into field. Choices are: brand_name, cartitem, dosage_strength, expiry_date, form, generic_name, history, is_deleted, item_no, last_updated, purchaseitems, quantity, saleitem
INFO 2024-11-20 20:40:09,231 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\homepage\views.py changed, reloading.
DEBUG 2024-11-20 20:40:09,231 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:40:09,751 autoreload Watching for file changes with StatReloader
ERROR 2024-11-20 20:42:25,461 log Internal Server Error: /inventory/new/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 477, in parse
    raise self.error(token, e)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 477, in parse
    raise self.error(token, e)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 482, in parse
    self.unclosed_block_tag(parse_until)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 543, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 7: 'block'. Looking for one of: endblock.
INFO 2024-11-20 20:47:52,262 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:47:52,262 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:47:53,085 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 20:49:24,127 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:49:24,133 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:49:24,735 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 20:49:38,022 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:49:38,022 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:49:38,804 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 20:50:15,189 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:50:15,189 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:50:15,901 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 20:50:24,875 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:50:24,875 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:50:25,574 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 20:50:34,489 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:50:34,489 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:50:35,013 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 20:50:39,552 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:50:39,552 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:50:40,154 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 20:51:53,418 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:51:53,421 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:51:54,129 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 20:52:14,840 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:52:14,840 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:52:15,456 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 20:52:43,602 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:52:43,602 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:52:44,138 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 20:52:53,928 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:52:53,928 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:52:54,405 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 20:52:57,757 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:52:57,757 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:52:58,262 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 20:53:43,755 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:53:43,757 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:53:44,456 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 20:53:57,679 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:53:57,687 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:53:58,405 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 20:54:09,472 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:54:09,477 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:54:10,205 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 20:54:20,163 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:54:20,171 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:54:20,930 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 20:54:29,937 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:54:29,945 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:54:30,599 autoreload Watching for file changes with StatReloader
ERROR 2024-11-20 20:54:35,764 log Internal Server Error: /inventory/fetch-product-details/1/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: fetch_product_details() got an unexpected keyword argument 'stock_id'
ERROR 2024-11-20 20:55:02,837 log Internal Server Error: /inventory/fetch-product-details/1/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: fetch_product_details() got an unexpected keyword argument 'stock_id'
INFO 2024-11-20 20:56:21,078 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:56:21,078 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:56:21,644 autoreload Watching for file changes with StatReloader
ERROR 2024-11-20 20:56:38,123 log Internal Server Error: /inventory/fetch-product-details/1/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: fetch_product_details() got an unexpected keyword argument 'stock_id'
ERROR 2024-11-20 20:56:43,280 log Internal Server Error: /inventory/fetch-product-details/1/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: fetch_product_details() got an unexpected keyword argument 'stock_id'
INFO 2024-11-20 20:57:05,040 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 20:57:05,040 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 20:57:05,563 autoreload Watching for file changes with StatReloader
ERROR 2024-11-20 20:57:09,446 log Internal Server Error: /inventory/fetch-product-details/1/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: fetch_product_details() got an unexpected keyword argument 'stock_id'
DEBUG 2024-11-20 20:57:13,534 views Selected items on GET: []
ERROR 2024-11-20 21:03:27,681 log Internal Server Error: /inventory/fetch-product-details/1/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: fetch_product_details() got an unexpected keyword argument 'stock_id'
INFO 2024-11-20 21:04:55,911 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 21:04:55,911 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:04:56,500 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 21:05:02,123 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 21:05:02,123 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:05:02,623 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 21:06:54,074 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\models.py changed, reloading.
DEBUG 2024-11-20 21:06:54,074 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:06:54,608 autoreload Watching for file changes with StatReloader
DEBUG 2024-11-20 21:06:58,492 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 21:06:58,543 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 21:07:02,816 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 21:07:44,782 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 21:11:03,439 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 21:13:19,265 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 21:14:20,249 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 21:15:02,962 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 21:15:39,593 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 21:16:04,894 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 21:17:14,377 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 21:17:30,241 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 21:18:40,646 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 21:19:01,904 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 21:19:09,807 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 21:21:01,328 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 21:21:06,061 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-20 21:21:14,969 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:24:57,731 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 21:27:24,903 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 21:27:24,911 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:27:25,768 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 21:31:14,348 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\forms.py changed, reloading.
DEBUG 2024-11-20 21:31:14,348 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:31:15,178 autoreload Watching for file changes with StatReloader
ERROR 2024-11-20 21:39:12,275 log Internal Server Error: /inventory/inventory/add-medicine/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py", line 334, in add_medicine
    return render(request, 'add_medicine.html', context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'add-medicine-history' not found. 'add-medicine-history' is not a valid view function or pattern name.
INFO 2024-11-20 21:40:59,500 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\urls.py changed, reloading.
DEBUG 2024-11-20 21:40:59,502 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:41:00,048 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 21:41:11,868 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 21:41:11,869 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:41:12,366 autoreload Watching for file changes with StatReloader
ERROR 2024-11-20 21:41:34,689 log Internal Server Error: /inventory/add-medicine-history/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'populate-dosage-forms' not found. 'populate-dosage-forms' is not a valid view function or pattern name.
INFO 2024-11-20 21:42:09,067 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 21:42:09,069 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:42:09,642 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 21:42:16,242 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\urls.py changed, reloading.
DEBUG 2024-11-20 21:42:16,244 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:42:16,721 autoreload Watching for file changes with StatReloader
ERROR 2024-11-20 21:42:20,402 log Internal Server Error: /inventory/add-medicine-history/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'populate-pharmacologic-categories' not found. 'populate-pharmacologic-categories' is not a valid view function or pattern name.
ERROR 2024-11-20 21:42:21,199 log Internal Server Error: /inventory/add-medicine-history/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'populate-pharmacologic-categories' not found. 'populate-pharmacologic-categories' is not a valid view function or pattern name.
ERROR 2024-11-20 21:42:21,392 log Internal Server Error: /inventory/add-medicine-history/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'populate-pharmacologic-categories' not found. 'populate-pharmacologic-categories' is not a valid view function or pattern name.
ERROR 2024-11-20 21:42:21,579 log Internal Server Error: /inventory/add-medicine-history/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'populate-pharmacologic-categories' not found. 'populate-pharmacologic-categories' is not a valid view function or pattern name.
ERROR 2024-11-20 21:42:21,781 log Internal Server Error: /inventory/add-medicine-history/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'populate-pharmacologic-categories' not found. 'populate-pharmacologic-categories' is not a valid view function or pattern name.
ERROR 2024-11-20 21:42:21,953 log Internal Server Error: /inventory/add-medicine-history/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'populate-pharmacologic-categories' not found. 'populate-pharmacologic-categories' is not a valid view function or pattern name.
ERROR 2024-11-20 21:42:22,131 log Internal Server Error: /inventory/add-medicine-history/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'populate-pharmacologic-categories' not found. 'populate-pharmacologic-categories' is not a valid view function or pattern name.
INFO 2024-11-20 21:43:13,295 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 21:43:13,297 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:43:13,759 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 21:43:24,718 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\urls.py changed, reloading.
DEBUG 2024-11-20 21:43:24,718 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:43:25,133 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 21:46:44,116 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 21:46:44,116 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:46:44,551 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 21:46:54,315 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\urls.py changed, reloading.
DEBUG 2024-11-20 21:46:54,316 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:46:54,733 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 21:51:07,885 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 21:51:07,886 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:51:08,293 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 21:51:19,102 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\urls.py changed, reloading.
DEBUG 2024-11-20 21:51:19,104 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:51:19,560 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 21:53:02,961 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 21:53:02,962 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:53:03,530 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 21:56:30,714 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\forms.py changed, reloading.
DEBUG 2024-11-20 21:56:30,716 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 21:56:31,250 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 22:00:17,672 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 22:00:17,673 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 22:00:18,070 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 22:04:17,426 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\forms.py changed, reloading.
DEBUG 2024-11-20 22:04:17,427 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 22:04:17,889 autoreload Watching for file changes with StatReloader
INFO 2024-11-20 22:05:00,693 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 22:05:00,694 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 22:05:01,216 autoreload Watching for file changes with StatReloader
ERROR 2024-11-20 22:05:37,704 log Internal Server Error: /inventory/fetch-product-details/1/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: fetch_product_details() got an unexpected keyword argument 'stock_id'
INFO 2024-11-20 22:06:54,303 autoreload C:\Users\NICK SENTERO\Downloads\SmartBotika (1)\SmartBotika\inventory\views.py changed, reloading.
DEBUG 2024-11-20 22:06:54,303 proactor_events Using proactor: IocpProactor
INFO 2024-11-20 22:06:54,908 autoreload Watching for file changes with StatReloader
ERROR 2024-11-20 22:19:19,221 log Internal Server Error: /inventory/fetch-product-details/3/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: fetch_product_details() got an unexpected keyword argument 'stock_id'
ERROR 2024-11-20 22:19:22,508 log Internal Server Error: /inventory/fetch-product-details/1/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: fetch_product_details() got an unexpected keyword argument 'stock_id'
ERROR 2024-11-20 22:19:23,153 log Internal Server Error: /inventory/fetch-product-details/2/
Traceback (most recent call last):
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\NICK SENTERO\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: fetch_product_details() got an unexpected keyword argument 'stock_id'
WARNING 2024-11-20 22:19:27,971 base Method Not Allowed (GET): /inventory/stock/out/
WARNING 2024-11-20 22:19:27,972 log Method Not Allowed: /inventory/stock/out/
WARNING 2024-11-20 22:19:36,956 base Method Not Allowed (GET): /inventory/stock/out/
WARNING 2024-11-20 22:19:36,958 log Method Not Allowed: /inventory/stock/out/
WARNING 2024-11-20 22:19:39,200 base Method Not Allowed (GET): /inventory/stock/out/
WARNING 2024-11-20 22:19:39,200 log Method Not Allowed: /inventory/stock/out/
DEBUG 2024-11-23 21:58:52,010 proactor_events Using proactor: IocpProactor
DEBUG 2024-11-23 21:58:52,062 proactor_events Using proactor: IocpProactor
INFO 2024-11-23 21:58:56,315 autoreload Watching for file changes with StatReloader
